<?xml version="1.0"?>
<robot name="my_amr" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Links -->
        <!-- Base Footprint -->
            <link name="base_footprint">
                <!-- Refer to Platform -->
            </link>

        <!-- Base (Chassis) -->
            <link name="base_link">
                <visual>
                    <geometry>
                        <box size="${c} ${c} ${b}"/>
                    </geometry>
                    <origin xyz="0 0 ${S1}" rpy="0 0 0"/>
                    <material name="red"/>
                </visual>
                <collision>
                    <geometry>
                        <box size="${c} ${c} ${b}"/>
                    </geometry>
                    <origin xyz="0 0 ${S1}" rpy="0 0 0"/>
                </collision>
                <xacro:box_inertia m="${body_mass}" l="${b}" w="${c}" h="${c}"
                                   xyz="0 0 ${S1}" rpy="0 0 0"/>
            </link>
            <joint name="base_footprint_base_joint" type="fixed">
                <parent link="base_footprint"/>
                <child link="base_link"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </joint>
            <gazebo reference="base_link">
                <material>Gazebo/Red</material>
            </gazebo>

        <!-- Wheels -->
            <xacro:macro name="wheel_link" params="prefix offset y">
                <link name="${prefix}_wheel_link">
                    <visual>
                        <geometry>
                            <cylinder radius="${r}" length="${d}"/>
                        </geometry>
                        <origin xyz="0 ${offset} 0" rpy="${pi/2.0} 0 0"/>
                        <material name="grey"/>
                    </visual>
                    <collision>
                        <geometry>
                            <cylinder radius="${r}" length="${d}"/>
                        </geometry>
                        <origin xyz="0 ${offset} 0" rpy="${pi/2.0} 0 0"/>
                    </collision>
                    <xacro:cylinder_inertia m="${wheel_mass}" r="${r}" h="${d}"
                                            xyz="0 ${offset} 0" rpy="${pi/2.0} 0 0"/>
                </link>
                <joint name="base_${prefix}_wheel_joint" type="continuous">
                    <parent link="base_link"/>
                    <child link="${prefix}_wheel_link"/>
                    <origin xyz="0 ${y} ${r}" rpy="0 0 0"/>
                    <axis xyz="0 1 0"/>
                </joint>
                <gazebo reference="${prefix}_wheel_link">
                    <material>Gazebo/Grey</material>
                </gazebo>
            </xacro:macro>
            <xacro:wheel_link prefix="right" offset="${wheel_offset}" y="${-S4}"/>
            <xacro:wheel_link prefix="left" offset="${-wheel_offset}" y="${S4}"/>

        <!-- Casters -->
            <xacro:macro name="caster_wheel_link" params="id x y">
                <link name="caster_wheel_${id}_link">
                    <visual>
                        <geometry>
                            <sphere radius="${r_caster}"/>
                        </geometry>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
                        <material name="black"/>
                    </visual>
                    <collision>
                        <geometry>
                            <sphere radius="${r_caster}"/>
                        </geometry>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
                    </collision>
                    <xacro:sphere_inertia m="${caster_mass}" r="${r_caster}" 
                                          xyz="0 0 0" rpy="0 0 0"/>
                </link>
                <joint name="base_caster_wheel_${id}_joint" type="fixed">
                    <parent link="base_link"/>
                    <child link="caster_wheel_${id}_link"/>
                    <origin xyz="${x} ${y} ${r_caster}" rpy="0 0 0"/>
                </joint>
                <gazebo reference="caster_wheel_${id}_link">
                    <material>Gazebo/Black</material>
                    <mu1 value="0.001"/>
                    <mu2 value="0.001"/>
                </gazebo>
            </xacro:macro>
            <xacro:caster_wheel_link id="1" x="${-S2}" y="${S3}"/>
            <xacro:caster_wheel_link id="2" x="${-S2}" y="${-S3}"/>
            <xacro:caster_wheel_link id="3" x="${S2}" y="${S3}"/>
            <xacro:caster_wheel_link id="4" x="${S2}" y="${-S3}"/>

        <!-- Roof (Optional) -->
            <link name="roof_link">
                <visual>
                    <geometry>
                        <box size="${c} ${c} ${roof_height}"/>
                    </geometry>
                    <origin xyz="0 0 ${roof_height/2.0}" rpy="0 0 0"/>
                    <material name="blue"/>
                </visual>
                <collision>
                    <geometry>
                        <box size="${c} ${c} ${roof_height}"/>
                    </geometry>
                    <origin xyz="0 0 ${roof_height/2.0}" rpy="0 0 0"/>
                </collision>
                <xacro:box_inertia m="${roof_mass}" l="${roof_height}" w="${c}" h="${c}"
                                   xyz="0 0 ${roof_height/2.0}" rpy="0 0 0"/>
            </link>
            <joint name="base_roof_joint" type="fixed">
                <parent link="base_link"/>
                <child link="roof_link"/>
                <origin xyz="0 0 ${S1 + (b + 2*r_caster - S1)}" rpy="0 0 0"/>
            </joint>
            <gazebo reference="roof_link">
                <material>Gazebo/Blue</material>
            </gazebo>

</robot>